//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHP.Service.BOSession {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dsws.businessobjects.com/2007/06/01")]
    public partial class DSWSException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string messageField;
        
        private string operationField;
        
        private string callStackTraceField;
        
        private string causeExceptionField;
        
        private string causeIDField;
        
        private string causeMessageField;
        
        private string causeDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("Operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string CallStackTrace {
            get {
                return this.callStackTraceField;
            }
            set {
                this.callStackTraceField = value;
                this.RaisePropertyChanged("CallStackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string CauseException {
            get {
                return this.causeExceptionField;
            }
            set {
                this.causeExceptionField = value;
                this.RaisePropertyChanged("CauseException");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string CauseID {
            get {
                return this.causeIDField;
            }
            set {
                this.causeIDField = value;
                this.RaisePropertyChanged("CauseID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string CauseMessage {
            get {
                return this.causeMessageField;
            }
            set {
                this.causeMessageField = value;
                this.RaisePropertyChanged("CauseMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string CauseDetail {
            get {
                return this.causeDetailField;
            }
            set {
                this.causeDetailField = value;
                this.RaisePropertyChanged("CauseDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServerInfoDetails))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01")]
    public partial class ServerInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] availableAuthenticationsField;
        
        private string versionField;
        
        private bool clusteredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AvailableAuthentications", IsNullable=true, Order=0)]
        public string[] AvailableAuthentications {
            get {
                return this.availableAuthenticationsField;
            }
            set {
                this.availableAuthenticationsField = value;
                this.RaisePropertyChanged("AvailableAuthentications");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Clustered {
            get {
                return this.clusteredField;
            }
            set {
                this.clusteredField = value;
                this.RaisePropertyChanged("Clustered");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01")]
    public partial class ServerInfoDetails : ServerInfo {
        
        private string[] authenticationsDescriptionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AuthenticationsDescription", IsNullable=true, Order=0)]
        public string[] AuthenticationsDescription {
            get {
                return this.authenticationsDescriptionField;
            }
            set {
                this.authenticationsDescriptionField = value;
                this.RaisePropertyChanged("AuthenticationsDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01", ConfigurationName="BOSession.SessionPort")]
    public interface SessionPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getServerInfo", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/getServerInfo", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ServerInfo")]
        AHP.Service.BOSession.ServerInfo getServerInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getServerInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ServerInfo")]
        System.Threading.Tasks.Task<AHP.Service.BOSession.ServerInfo> getServerInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getServerInfoDetails", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/getServerInfoDetails", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ServerInfoDetails")]
        AHP.Service.BOSession.ServerInfoDetails getServerInfoDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getServerInfoDetails", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ServerInfoDetails")]
        System.Threading.Tasks.Task<AHP.Service.BOSession.ServerInfoDetails> getServerInfoDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getVersion", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/getVersion", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Version")]
        string getVersion(string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getVersion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Version")]
        System.Threading.Tasks.Task<string> getVersionAsync(string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/resetSessionTimeOut", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/resetSessionTimeOut", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void resetSessionTimeOut(string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/resetSessionTimeOut", ReplyAction="*")]
        System.Threading.Tasks.Task resetSessionTimeOutAsync(string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/login", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/login", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SessionInfo")]
        AHP.Service.BOSession.SessionInfo login(AHP.Service.BOSession.Credential credential, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/login", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SessionInfo")]
        System.Threading.Tasks.Task<AHP.Service.BOSession.SessionInfo> loginAsync(AHP.Service.BOSession.Credential credential, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/loginWithToken", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/loginWithToken", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SessionInfo")]
        AHP.Service.BOSession.SessionInfo loginWithToken(string loginToken, string locale, string timeZone, string ReportedIPAddress, string ReportedHostName, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/loginWithToken", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SessionInfo")]
        System.Threading.Tasks.Task<AHP.Service.BOSession.SessionInfo> loginWithTokenAsync(string loginToken, string locale, string timeZone, string ReportedIPAddress, string ReportedHostName, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/loginWithSerializedSession", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/loginWithSerializedSession", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SessionInfo")]
        AHP.Service.BOSession.SessionInfo loginWithSerializedSession(string loginSerializedSession, string locale, string timeZone, string ReportedIPAddress, string ReportedHostName, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/loginWithSerializedSession", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SessionInfo")]
        System.Threading.Tasks.Task<AHP.Service.BOSession.SessionInfo> loginWithSerializedSessionAsync(string loginSerializedSession, string locale, string timeZone, string ReportedIPAddress, string ReportedHostName, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/logout", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/logout", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void logout(string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/logout", ReplyAction="*")]
        System.Threading.Tasks.Task logoutAsync(string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/changePassword", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/changePassword", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void changePassword(string session, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/changePassword", ReplyAction="*")]
        System.Threading.Tasks.Task changePasswordAsync(string session, string oldPassword, string newPassword);
        
        // CODEGEN: Parameter 'Dictionary' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getDictionary", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/getDictionary", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Dictionary")]
        AHP.Service.BOSession.getDictionaryResponse getDictionary(AHP.Service.BOSession.getDictionaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getDictionary", ReplyAction="*")]
        System.Threading.Tasks.Task<AHP.Service.BOSession.getDictionaryResponse> getDictionaryAsync(AHP.Service.BOSession.getDictionaryRequest request);
        
        // CODEGEN: Parameter 'entries' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/setDictionary", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/setDictionary", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AHP.Service.BOSession.setDictionaryResponse setDictionary(AHP.Service.BOSession.setDictionaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/setDictionary", ReplyAction="*")]
        System.Threading.Tasks.Task<AHP.Service.BOSession.setDictionaryResponse> setDictionaryAsync(AHP.Service.BOSession.setDictionaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getSessionInfo", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/getSessionInfo", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SessionInfo")]
        AHP.Service.BOSession.SessionInfo getSessionInfo(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getSessionInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SessionInfo")]
        System.Threading.Tasks.Task<AHP.Service.BOSession.SessionInfo> getSessionInfoAsync(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/setPVLocale", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/setPVLocale", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setPVLocale(string sessionID, string PVLocale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/setPVLocale", ReplyAction="*")]
        System.Threading.Tasks.Task setPVLocaleAsync(string sessionID, string PVLocale);
        
        // CODEGEN: Parameter 'SupportedPVLocales' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getSupportedPVLs", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/getSupportedPVLs", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SupportedPVLocales")]
        AHP.Service.BOSession.getSupportedPVLsResponse getSupportedPVLs(AHP.Service.BOSession.getSupportedPVLsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getSupportedPVLs", ReplyAction="*")]
        System.Threading.Tasks.Task<AHP.Service.BOSession.getSupportedPVLsResponse> getSupportedPVLsAsync(AHP.Service.BOSession.getSupportedPVLsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/setSecondaryCredential", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/setSecondaryCredential", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setSecondaryCredential(string session, string key, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/setSecondaryCredential", ReplyAction="*")]
        System.Threading.Tasks.Task setSecondaryCredentialAsync(string session, string key, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getSecondaryCredential", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/getSecondaryCredential", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="value")]
        string getSecondaryCredential(string session, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getSecondaryCredential", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="value")]
        System.Threading.Tasks.Task<string> getSecondaryCredentialAsync(string session, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/removeSecondaryCredential", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/removeSecondaryCredential", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void removeSecondaryCredential(string session, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/removeSecondaryCredential", ReplyAction="*")]
        System.Threading.Tasks.Task removeSecondaryCredentialAsync(string session, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getSAPAssertionTicket", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/getSAPAssertionTicket", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SAPTicket")]
        string getSAPAssertionTicket(string session, string targetSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/getSAPAssertionTicket", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SAPTicket")]
        System.Threading.Tasks.Task<string> getSAPAssertionTicketAsync(string session, string targetSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/createLogonToken", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/createLogonToken", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="logonToken")]
        string createLogonToken(string session, int validMinutes, int validNumOfLogons);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/createLogonToken", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="logonToken")]
        System.Threading.Tasks.Task<string> createLogonTokenAsync(string session, int validMinutes, int validNumOfLogons);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/releaseToken", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/releaseToken", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void releaseToken(string session, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/releaseToken", ReplyAction="*")]
        System.Threading.Tasks.Task releaseTokenAsync(string session, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/releaseToken", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AHP.Service.BOSession.DSWSException), Action="http://session.dsws.businessobjects.com/2007/06/01/releaseToken", Name="DSWSException", Namespace="http://dsws.businessobjects.com/2007/06/01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SAMLSSOTicket")]
        string getSAMLSSOAssertionTicket(string session, string spHost, int spPort);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://session.dsws.businessobjects.com/2007/06/01/releaseToken", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SAMLSSOTicket")]
        System.Threading.Tasks.Task<string> getSAMLSSOAssertionTicketAsync(string session, string spHost, int spPort);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnterpriseCredential))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01")]
    public partial class Credential : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01")]
    public partial class EnterpriseCredential : Credential {
        
        private string loginField;
        
        private string passwordField;
        
        private string localeField;
        
        private string timeZoneField;
        
        private string domainField;
        
        private string authTypeField;
        
        private string reportedIPAddressField;
        
        private string reportedHostNameField;
        
        private string clientTypeField;
        
        private string policyIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
                this.RaisePropertyChanged("Locale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
                this.RaisePropertyChanged("TimeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("Domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AuthType {
            get {
                return this.authTypeField;
            }
            set {
                this.authTypeField = value;
                this.RaisePropertyChanged("AuthType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReportedIPAddress {
            get {
                return this.reportedIPAddressField;
            }
            set {
                this.reportedIPAddressField = value;
                this.RaisePropertyChanged("ReportedIPAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReportedHostName {
            get {
                return this.reportedHostNameField;
            }
            set {
                this.reportedHostNameField = value;
                this.RaisePropertyChanged("ReportedHostName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string clientType {
            get {
                return this.clientTypeField;
            }
            set {
                this.clientTypeField = value;
                this.RaisePropertyChanged("clientType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string policyID {
            get {
                return this.policyIDField;
            }
            set {
                this.policyIDField = value;
                this.RaisePropertyChanged("policyID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01")]
    public partial class SessionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UserRight[] userRightsField;
        
        private WSResource[] wSResourceListField;
        
        private string loginInfoField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string localeField;
        
        private string pVLocaleField;
        
        private bool mustChangePasswordField;
        
        private string sessionIDField;
        
        private string defaultTokenField;
        
        private int timeOutField;
        
        private string userCUIDField;
        
        private string serializedSessionField;
        
        private string timeZoneField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserRights", IsNullable=true, Order=0)]
        public UserRight[] UserRights {
            get {
                return this.userRightsField;
            }
            set {
                this.userRightsField = value;
                this.RaisePropertyChanged("UserRights");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WSResourceList", IsNullable=true, Order=1)]
        public WSResource[] WSResourceList {
            get {
                return this.wSResourceListField;
            }
            set {
                this.wSResourceListField = value;
                this.RaisePropertyChanged("WSResourceList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string LoginInfo {
            get {
                return this.loginInfoField;
            }
            set {
                this.loginInfoField = value;
                this.RaisePropertyChanged("LoginInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
                this.RaisePropertyChanged("Locale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PVLocale {
            get {
                return this.pVLocaleField;
            }
            set {
                this.pVLocaleField = value;
                this.RaisePropertyChanged("PVLocale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool MustChangePassword {
            get {
                return this.mustChangePasswordField;
            }
            set {
                this.mustChangePasswordField = value;
                this.RaisePropertyChanged("MustChangePassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultToken {
            get {
                return this.defaultTokenField;
            }
            set {
                this.defaultTokenField = value;
                this.RaisePropertyChanged("DefaultToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TimeOut {
            get {
                return this.timeOutField;
            }
            set {
                this.timeOutField = value;
                this.RaisePropertyChanged("TimeOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserCUID {
            get {
                return this.userCUIDField;
            }
            set {
                this.userCUIDField = value;
                this.RaisePropertyChanged("UserCUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SerializedSession {
            get {
                return this.serializedSessionField;
            }
            set {
                this.serializedSessionField = value;
                this.RaisePropertyChanged("SerializedSession");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
                this.RaisePropertyChanged("TimeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01")]
    public partial class UserRight : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01")]
    public partial class WSResource : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string uRLField;
        
        private string wSTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WSType {
            get {
                return this.wSTypeField;
            }
            set {
                this.wSTypeField = value;
                this.RaisePropertyChanged("WSType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01")]
    public enum DictionaryType {
        
        /// <remarks/>
        USER,
        
        /// <remarks/>
        SERVER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01")]
    public partial class Entry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object valueField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDictionary", WrapperNamespace="http://session.dsws.businessobjects.com/2007/06/01", IsWrapped=true)]
    public partial class getDictionaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01", Order=0)]
        public string session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01", Order=1)]
        public AHP.Service.BOSession.DictionaryType dictionary;
        
        public getDictionaryRequest() {
        }
        
        public getDictionaryRequest(string session, AHP.Service.BOSession.DictionaryType dictionary) {
            this.session = session;
            this.dictionary = dictionary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDictionaryResponse", WrapperNamespace="http://session.dsws.businessobjects.com/2007/06/01", IsWrapped=true)]
    public partial class getDictionaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Dictionary", IsNullable=true)]
        public AHP.Service.BOSession.Entry[] Dictionary;
        
        public getDictionaryResponse() {
        }
        
        public getDictionaryResponse(AHP.Service.BOSession.Entry[] Dictionary) {
            this.Dictionary = Dictionary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDictionary", WrapperNamespace="http://session.dsws.businessobjects.com/2007/06/01", IsWrapped=true)]
    public partial class setDictionaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01", Order=0)]
        public string session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01", Order=1)]
        public AHP.Service.BOSession.DictionaryType dictionary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("entries", IsNullable=true)]
        public AHP.Service.BOSession.Entry[] entries;
        
        public setDictionaryRequest() {
        }
        
        public setDictionaryRequest(string session, AHP.Service.BOSession.DictionaryType dictionary, AHP.Service.BOSession.Entry[] entries) {
            this.session = session;
            this.dictionary = dictionary;
            this.entries = entries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDictionaryResponse", WrapperNamespace="http://session.dsws.businessobjects.com/2007/06/01", IsWrapped=true)]
    public partial class setDictionaryResponse {
        
        public setDictionaryResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSupportedPVLs", WrapperNamespace="http://session.dsws.businessobjects.com/2007/06/01", IsWrapped=true)]
    public partial class getSupportedPVLsRequest {
        
        public getSupportedPVLsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSupportedPVLsResponse", WrapperNamespace="http://session.dsws.businessobjects.com/2007/06/01", IsWrapped=true)]
    public partial class getSupportedPVLsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://session.dsws.businessobjects.com/2007/06/01", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PVLocale")]
        public string[] SupportedPVLocales;
        
        public getSupportedPVLsResponse() {
        }
        
        public getSupportedPVLsResponse(string[] SupportedPVLocales) {
            this.SupportedPVLocales = SupportedPVLocales;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionPortChannel : AHP.Service.BOSession.SessionPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionPortClient : System.ServiceModel.ClientBase<AHP.Service.BOSession.SessionPort>, AHP.Service.BOSession.SessionPort {
        
        public SessionPortClient() {
        }
        
        public SessionPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AHP.Service.BOSession.ServerInfo getServerInfo() {
            return base.Channel.getServerInfo();
        }
        
        public System.Threading.Tasks.Task<AHP.Service.BOSession.ServerInfo> getServerInfoAsync() {
            return base.Channel.getServerInfoAsync();
        }
        
        public AHP.Service.BOSession.ServerInfoDetails getServerInfoDetails() {
            return base.Channel.getServerInfoDetails();
        }
        
        public System.Threading.Tasks.Task<AHP.Service.BOSession.ServerInfoDetails> getServerInfoDetailsAsync() {
            return base.Channel.getServerInfoDetailsAsync();
        }
        
        public string getVersion(string session) {
            return base.Channel.getVersion(session);
        }
        
        public System.Threading.Tasks.Task<string> getVersionAsync(string session) {
            return base.Channel.getVersionAsync(session);
        }
        
        public void resetSessionTimeOut(string session) {
            base.Channel.resetSessionTimeOut(session);
        }
        
        public System.Threading.Tasks.Task resetSessionTimeOutAsync(string session) {
            return base.Channel.resetSessionTimeOutAsync(session);
        }
        
        public AHP.Service.BOSession.SessionInfo login(AHP.Service.BOSession.Credential credential, string version) {
            return base.Channel.login(credential, version);
        }
        
        public System.Threading.Tasks.Task<AHP.Service.BOSession.SessionInfo> loginAsync(AHP.Service.BOSession.Credential credential, string version) {
            return base.Channel.loginAsync(credential, version);
        }
        
        public AHP.Service.BOSession.SessionInfo loginWithToken(string loginToken, string locale, string timeZone, string ReportedIPAddress, string ReportedHostName, string version) {
            return base.Channel.loginWithToken(loginToken, locale, timeZone, ReportedIPAddress, ReportedHostName, version);
        }
        
        public System.Threading.Tasks.Task<AHP.Service.BOSession.SessionInfo> loginWithTokenAsync(string loginToken, string locale, string timeZone, string ReportedIPAddress, string ReportedHostName, string version) {
            return base.Channel.loginWithTokenAsync(loginToken, locale, timeZone, ReportedIPAddress, ReportedHostName, version);
        }
        
        public AHP.Service.BOSession.SessionInfo loginWithSerializedSession(string loginSerializedSession, string locale, string timeZone, string ReportedIPAddress, string ReportedHostName, string version) {
            return base.Channel.loginWithSerializedSession(loginSerializedSession, locale, timeZone, ReportedIPAddress, ReportedHostName, version);
        }
        
        public System.Threading.Tasks.Task<AHP.Service.BOSession.SessionInfo> loginWithSerializedSessionAsync(string loginSerializedSession, string locale, string timeZone, string ReportedIPAddress, string ReportedHostName, string version) {
            return base.Channel.loginWithSerializedSessionAsync(loginSerializedSession, locale, timeZone, ReportedIPAddress, ReportedHostName, version);
        }
        
        public void logout(string session) {
            base.Channel.logout(session);
        }
        
        public System.Threading.Tasks.Task logoutAsync(string session) {
            return base.Channel.logoutAsync(session);
        }
        
        public void changePassword(string session, string oldPassword, string newPassword) {
            base.Channel.changePassword(session, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task changePasswordAsync(string session, string oldPassword, string newPassword) {
            return base.Channel.changePasswordAsync(session, oldPassword, newPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AHP.Service.BOSession.getDictionaryResponse AHP.Service.BOSession.SessionPort.getDictionary(AHP.Service.BOSession.getDictionaryRequest request) {
            return base.Channel.getDictionary(request);
        }
        
        public AHP.Service.BOSession.Entry[] getDictionary(string session, AHP.Service.BOSession.DictionaryType dictionary) {
            AHP.Service.BOSession.getDictionaryRequest inValue = new AHP.Service.BOSession.getDictionaryRequest();
            inValue.session = session;
            inValue.dictionary = dictionary;
            AHP.Service.BOSession.getDictionaryResponse retVal = ((AHP.Service.BOSession.SessionPort)(this)).getDictionary(inValue);
            return retVal.Dictionary;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AHP.Service.BOSession.getDictionaryResponse> AHP.Service.BOSession.SessionPort.getDictionaryAsync(AHP.Service.BOSession.getDictionaryRequest request) {
            return base.Channel.getDictionaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<AHP.Service.BOSession.getDictionaryResponse> getDictionaryAsync(string session, AHP.Service.BOSession.DictionaryType dictionary) {
            AHP.Service.BOSession.getDictionaryRequest inValue = new AHP.Service.BOSession.getDictionaryRequest();
            inValue.session = session;
            inValue.dictionary = dictionary;
            return ((AHP.Service.BOSession.SessionPort)(this)).getDictionaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AHP.Service.BOSession.setDictionaryResponse AHP.Service.BOSession.SessionPort.setDictionary(AHP.Service.BOSession.setDictionaryRequest request) {
            return base.Channel.setDictionary(request);
        }
        
        public void setDictionary(string session, AHP.Service.BOSession.DictionaryType dictionary, AHP.Service.BOSession.Entry[] entries) {
            AHP.Service.BOSession.setDictionaryRequest inValue = new AHP.Service.BOSession.setDictionaryRequest();
            inValue.session = session;
            inValue.dictionary = dictionary;
            inValue.entries = entries;
            AHP.Service.BOSession.setDictionaryResponse retVal = ((AHP.Service.BOSession.SessionPort)(this)).setDictionary(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AHP.Service.BOSession.setDictionaryResponse> AHP.Service.BOSession.SessionPort.setDictionaryAsync(AHP.Service.BOSession.setDictionaryRequest request) {
            return base.Channel.setDictionaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<AHP.Service.BOSession.setDictionaryResponse> setDictionaryAsync(string session, AHP.Service.BOSession.DictionaryType dictionary, AHP.Service.BOSession.Entry[] entries) {
            AHP.Service.BOSession.setDictionaryRequest inValue = new AHP.Service.BOSession.setDictionaryRequest();
            inValue.session = session;
            inValue.dictionary = dictionary;
            inValue.entries = entries;
            return ((AHP.Service.BOSession.SessionPort)(this)).setDictionaryAsync(inValue);
        }
        
        public AHP.Service.BOSession.SessionInfo getSessionInfo(string sessionID) {
            return base.Channel.getSessionInfo(sessionID);
        }
        
        public System.Threading.Tasks.Task<AHP.Service.BOSession.SessionInfo> getSessionInfoAsync(string sessionID) {
            return base.Channel.getSessionInfoAsync(sessionID);
        }
        
        public void setPVLocale(string sessionID, string PVLocale) {
            base.Channel.setPVLocale(sessionID, PVLocale);
        }
        
        public System.Threading.Tasks.Task setPVLocaleAsync(string sessionID, string PVLocale) {
            return base.Channel.setPVLocaleAsync(sessionID, PVLocale);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AHP.Service.BOSession.getSupportedPVLsResponse AHP.Service.BOSession.SessionPort.getSupportedPVLs(AHP.Service.BOSession.getSupportedPVLsRequest request) {
            return base.Channel.getSupportedPVLs(request);
        }
        
        public string[] getSupportedPVLs() {
            AHP.Service.BOSession.getSupportedPVLsRequest inValue = new AHP.Service.BOSession.getSupportedPVLsRequest();
            AHP.Service.BOSession.getSupportedPVLsResponse retVal = ((AHP.Service.BOSession.SessionPort)(this)).getSupportedPVLs(inValue);
            return retVal.SupportedPVLocales;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AHP.Service.BOSession.getSupportedPVLsResponse> AHP.Service.BOSession.SessionPort.getSupportedPVLsAsync(AHP.Service.BOSession.getSupportedPVLsRequest request) {
            return base.Channel.getSupportedPVLsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AHP.Service.BOSession.getSupportedPVLsResponse> getSupportedPVLsAsync() {
            AHP.Service.BOSession.getSupportedPVLsRequest inValue = new AHP.Service.BOSession.getSupportedPVLsRequest();
            return ((AHP.Service.BOSession.SessionPort)(this)).getSupportedPVLsAsync(inValue);
        }
        
        public void setSecondaryCredential(string session, string key, string value) {
            base.Channel.setSecondaryCredential(session, key, value);
        }
        
        public System.Threading.Tasks.Task setSecondaryCredentialAsync(string session, string key, string value) {
            return base.Channel.setSecondaryCredentialAsync(session, key, value);
        }
        
        public string getSecondaryCredential(string session, string key) {
            return base.Channel.getSecondaryCredential(session, key);
        }
        
        public System.Threading.Tasks.Task<string> getSecondaryCredentialAsync(string session, string key) {
            return base.Channel.getSecondaryCredentialAsync(session, key);
        }
        
        public void removeSecondaryCredential(string session, string key) {
            base.Channel.removeSecondaryCredential(session, key);
        }
        
        public System.Threading.Tasks.Task removeSecondaryCredentialAsync(string session, string key) {
            return base.Channel.removeSecondaryCredentialAsync(session, key);
        }
        
        public string getSAPAssertionTicket(string session, string targetSystem) {
            return base.Channel.getSAPAssertionTicket(session, targetSystem);
        }
        
        public System.Threading.Tasks.Task<string> getSAPAssertionTicketAsync(string session, string targetSystem) {
            return base.Channel.getSAPAssertionTicketAsync(session, targetSystem);
        }
        
        public string createLogonToken(string session, int validMinutes, int validNumOfLogons) {
            return base.Channel.createLogonToken(session, validMinutes, validNumOfLogons);
        }
        
        public System.Threading.Tasks.Task<string> createLogonTokenAsync(string session, int validMinutes, int validNumOfLogons) {
            return base.Channel.createLogonTokenAsync(session, validMinutes, validNumOfLogons);
        }
        
        public void releaseToken(string session, string token) {
            base.Channel.releaseToken(session, token);
        }
        
        public System.Threading.Tasks.Task releaseTokenAsync(string session, string token) {
            return base.Channel.releaseTokenAsync(session, token);
        }
        
        public string getSAMLSSOAssertionTicket(string session, string spHost, int spPort) {
            return base.Channel.getSAMLSSOAssertionTicket(session, spHost, spPort);
        }
        
        public System.Threading.Tasks.Task<string> getSAMLSSOAssertionTicketAsync(string session, string spHost, int spPort) {
            return base.Channel.getSAMLSSOAssertionTicketAsync(session, spHost, spPort);
        }
    }
}
